


<table>
    <thead>
        <tr>
            <th>
                Firstname
            </th>
        </tr>
        <tr>
            <th>
                Lastname
            </th>
        </tr>
        <tr>
            <th>
                Umsatz
            </th>
        </tr>
        <tr>
            <th>
                Ändern
            </th>
        </tr>
        <tr>
            <th>
                Löschen
            </th>
        </tr>



    </thead>
    <tbody>
        <tr>
            <td>

            </td>
            <td>

            </td>
            <td>

            </td>
        </tr>
    </tbody>




</table>
<?php
foreach($allUsers as $users){
       print_r($users);
};

?>