<table class="table table-striped">
    <thead>
        <tr>
            <th>
                Firstname
            </th>

            <th>
                Lastname
            </th>

            <th>
                Umsatz
            </th>

            <th>
                Ändern
            </th>

            <th>
                Löschen
            </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($allUsers as $users):?>
        <tr>
            <td>
                <?php print_r($users['name']);?>
            </td>
            <td>
                <?php print_r($users['password']);?>
            </td>
            <td>
                <?php print_r($users['role']);?>
            </td>
            <td>
                <div class="btn btn-default">
                    Change
                </div>
            </td>
            <td>
                <div class="btn btn-default">
                    Löschen
                </div>
            </td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>
