<div class="jumbotron text-center">
    <h1 class="table-location">Menu</h1>
</div>

<!-- Nav tabs -->
<div class="container choose-article">
    <ul class="nav nav-tabs">
        <?php foreach($category as $categories):?>
            <li><a data-toggle="tab" class="<?php print_r($categories['id']);?>" href="#<?php print_r($categories['id']);?>"><?php print_r($categories['name']);?></a></li>
        <?php endforeach;?>
    </ul>

    <div class="tab-content">
        <?php //get the value of the tabs ?>
        <?php foreach($category as $categories):?>
            <div id="<?php print_r($categories['id']);?>" class="tab-pane fade in ">
                <h3><?php print_r($categories['name']);?></h3>
                <div class="table-responsive  col-xs-6">
                    <table class="table table-hover">

                        <tbody>
                        <?php foreach($joinCategories as $joins):?>
                            <?php if($joins['category'] == $categories['id']):?>
                                <tr id="table_value" class="table-row-<?php print_r($joins['id'])?>" value="<?php print_r($joins['price'])?>">
                                    <td>
                                        <?php print_r($joins['name']);?>
                                    </td>
                                    <td>
                                        <?php print_r($joins['price'])?>
                                    </td>
                                </tr>
                            <?php endif;?>
                        <?php endforeach;?>
                        </tbody>

                    </table>
                </div>
                <p></p>
            </div>
        <?php endforeach;?>

        <div class="col-xs-6 counter container">
            <h2>Bestellungen</h2>
            <div class="form-group">
                <ul class="list-group" id="listen">
                    <!--GET SELECTED ORDERS -->
                </ul>
                <div>
                    <h3 class="money"></h3>
                    <input type="hidden" class="sum">
                </div>

<!--                <form method="post">-->
                    <button id="button-submit-order" class="btn btn-default">Submit</button>
<!--                </form>-->

            </div>
        </div>
    </div>
</div>

<?php //show all tables
    foreach($tables as $table):?>
    <div class="but col-xs-3">
        <button class="btn btn-default" id="<?php print_r($table['id'])?>" value="<?php print_r($table['name'])?>">
            <i class="fa fa-users" aria-hidden="true"></i>
            <?php print_r($table['name'])?>
        </button>
    </div>
<?php endforeach;?>





<script>
    $(function(){

        ///////////////////////////////////////////
        //
        //At first choose the table, before you can select the order
        //
        //////////////////////////////////////////
        $('.choose-article').hide();


        $( ".but" ).on('click','button',function(e){
            e.preventDefault();

            //Get selected table name,id to show which table the waitress selected
            var table_id = $(this).attr('id');
            var table_name = $(this).attr('value');

            $('.table-location').html(table_id);
            $(".but").hide();
            $('.choose-article').show();
            //

            //
            var i=0;
            var fibonacci=0;
            var value;
            var minus_obj;

            $( ".1" ).trigger('click');
            $('.counter').hide();

            //Menu
            //select orders from menu
            $( ".table" ).on('click','tr',function(e){
                e.preventDefault();
                $('.counter').show();
                var class_id = $(this).attr('class');
                value = $(this).attr('value');
                fibonacci= parseFloat(fibonacci)+parseFloat(value);
                $( '.money' ).html(parseFloat(fibonacci).toFixed(2));
                $( '.sum' ).attr('value', parseFloat(fibonacci).toFixed(2));
                var id = $(this).text();
                var li = "<li class='class_id_"+class_id+"' id='list-value-"+i+"-id' value='"+value+"'>"+id+"</li>";
                //Now use appendChild and add it to the list!
                $( "#listen" ).append(li);
                i++;
            });

            //Bill
            //show/hide/calculate order and money
            $( '#listen' ).on('click','li',function(e){
                $(e.target).remove();

                minus_obj = $(this).attr('value');

                if(minus_obj > fibonacci)
                {
                    fibonacci = parseFloat(minus_obj) - parseFloat(fibonacci);
                }
                else if(minus_obj < fibonacci)
                {
                    fibonacci =  parseFloat(fibonacci) - parseFloat(minus_obj);

                }
                else if(minus_obj = fibonacci)
                {
                    fibonacci = 0;
                }
                if($('.money').html() == minus_obj){

                    $('.counter').hide();
                }

                $( '.money' ).html(parseFloat(fibonacci).toFixed(2));
                $( '.sum' ).attr('value', parseFloat(fibonacci).toFixed(2));

            });

            //POST Data
            //post orders

            var orderInformation={};

            $('#button-submit-order').click(function(){
                var j = 1;
                //All selected order saved in object
                var thisOrders = {};

                //current selected table
                var getTableName = $('.table-location').html();

                var orderPrice =  $( '.sum' ).val();


                //current waitress-name
                var getWaitressName = '<?php print_r($this->identity())?>';

                //get all orders
                $(".list-group li").each(function(){
                    thisOrders['article'+ j++] = $(this).attr('class');
                });

                orderInformation['TableId'] = getTableName;
                orderInformation['UserName'] = getWaitressName;
                orderInformation['OrderPrice'] = orderPrice;
                orderInformation['SelectedArticles'] = thisOrders;

                console.log(orderInformation);

                callApi('POST','/waitress-rest',orderInformation);

                $('.counter').submit();

            });

        });

        //get automatically the data from restful
        /* var inter =  setInterval(function() {
         var clearInter = setInterval(function() {

         clearInterval(clearInter);
         /!*alert("clear"+test);*!/
         });
         },5000);*/

        
        function callApi(met,path,object) {

            var method = met;
            var url = path;
            var data = object;

            $.ajax({
                url: url,
                type: method,
                data: data,
                dataType: "json",
                headers: {},
                success: function(data) {
                    alert(data);
                },
                error: function (data) {
                    console.debug("Fail" + JSON.stringify(JSON.stringify(data)));
                }
            });
        }

    });
</script>