<?php
/**
 * Created by PhpStorm.
 * User: Pawel_000
 * Date: 12.03.2017
 * Time: 16:17
 */

namespace Application\Controller;


use Zend\Authentication\Adapter\DbTable;
use Zend\Authentication\AuthenticationService;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;



class DashboardController extends AbstractActionController
{
    private $authService;

   public function onDispatch(MvcEvent $e)
   {
       $this->authService = new AuthenticationService;
       if ($this->authService->getIdentity()!= true){
           $this->redirect()->toRoute('home');
       }
       return parent::onDispatch($e); // TODO: Change the autogenerated stub
   }

    public function indexAction()
    {

        return new ViewModel();
    }
    public function kitchenAction()
    {
        if($this->identity() != null){

            $userEmail = $this->identity();

            print_r($userEmail);
        }
        return new ViewModel();
    }
    public function waitressAction()
    {
        if($this->identity() != null){

            $userEmail = $this->identity();

            print_r($userEmail);
        }

        return new ViewModel();
    }

}