<?php
/**
 * User: Alice in wonderland
 * Date: 01.04.2017
 * Time: 13:17
 */

namespace Application\Controller;


use Zend\Authentication\AuthenticationService;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;

class KitchenController extends AbstractActionController
{
    private $authService;
    public function onDispatch(MvcEvent $e)
    {
        $this->authService = new AuthenticationService;
        if ($this->authService->getIdentity() != true){
            $this->redirect()->toRoute('home');
        }
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }

public function indexAction()
{
    return new ViewModel();
}
}