<?php
/**
 * User: Alice in wonderland
 * Date: 01.04.2017
 * Time: 13:17
 */

namespace Application\Controller;


use Application\Model\DataInterface;
use Zend\Authentication\AuthenticationService;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;

class WaitressController extends AbstractActionController
{

    private $authService;
    private $_dbInterface;

    public function onDispatch(MvcEvent $e)
    {
        $this->authService = new AuthenticationService;
        if ($this->authService->getIdentity() != true){
            $this->redirect()->toRoute('home');
        }
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }
    public function __construct(DataInterface $dbInterface)
    {
        $this->_dbInterface = $dbInterface;
    }

    public function indexAction()
    {
        $getCategory = $this->_dbInterface->getCategories();
        $jointest = $this->_dbInterface->getjoins();

        if($this->getRequest()->isPost()){
            $data = $this->getRequest()->getPost();
            print_r($data);
        }


        return new ViewModel([
            'category' => $getCategory,
            'joinCategories' => $jointest,
        ]);

    }
}