<?php
//test roger
//echo $this->form()->render($form);
$this->headTitle('Sign in');

//set Bootstrap-Style for the form
$form->get('username')->setAttributes([
    'class' => 'form-control',
    'placeholder' => '#Username',
    'required' => true,
    'autofocus' => true
]);

$form->get('password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Type password here',
    'required' => true,
]);

$form->get('worker')->setAttributes([
   'class'=>'form-control',
    'required' => true
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

?>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <!-- Use the _invoke method to render   -->
            <?= $this->formLabel($form->get('username')); ?>
            <?= $this->formElement($form->get('username')); ?>
            <?= $this->formElementErrors($form->get('username')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement()->render($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formElement()->render($form->get('worker')); ?>
        </div>

        <div class="form-group">
            <?= $this->formElement($form->get('submit')); ?>
        </div>

        <?= $this->form()->closeTag();?>
    </div>
</div>


<script>

    //<div id="div1"><h2></h2></div>
    //   $("#div1").load("/shodan-rest");

    //   var inter =  setInterval(function() {
    //
    //        $("#div1").load("/shodan-rest");
    //        clearInterval(inter)
    //    },1000);
</script>